import { useNavigate } from 'react-router-dom';
import { TrendingUp, AlertTriangle, ArrowLeft, BrainCircuit, TerminalSquare } from 'lucide-react';

export default function InterviewSummary() {
    const navigate = useNavigate();

    // In real app, fetch from /interviews/{sessionId}/summary
    const summary = {
        overall_score: 87,
        communication_score: 92,
        technical_score: 85,
        standout_moments: [
            { moment: "Deep knowledge of React reconciler", transcript_ref: "I handled the state update using a custom hook that bypasses the virtual DOM constraint..." }
        ],
        red_flags: [
            { moment: "Hesitant on backend auth protocols", transcript_ref: "Uh, I think OAuth uses a token, I haven't implemented it directly." }
        ]
    };

    return (
        <div className="max-w-5xl mx-auto space-y-8 pb-12 font-body text-fintech-cream">
            
            <button onClick={() => navigate(-1)} className="flex items-center text-fintech-ash hover:text-fintech-amber transition font-terminal text-[11px] uppercase tracking-widest group">
                <ArrowLeft className="w-4 h-4 mr-3 group-hover:-translate-x-1 transition-transform" /> Retract to Pipeline
            </button>

            <div className="flex justify-between items-end bg-[#1C202E] p-8 rounded-xl border border-fintech-border shadow-[0_20px_40px_rgba(0,0,0,0.4)] relative overflow-hidden">
                <div className="absolute top-0 right-0 w-2 h-full bg-fintech-amber"></div>
                <div>
                    <h1 className="text-3xl font-editorial font-medium tracking-wide mb-3">Diagnostic Summary</h1>
                    <p className="font-terminal text-[10px] uppercase tracking-[0.2em] text-[#63A583] flex items-center">
                        <BrainCircuit className="w-4 h-4 mr-2" /> Generated by Agent // Strict Mode
                    </p>
                </div>
                <div className="bg-fintech-amber text-fintech-base px-8 py-4 rounded shadow-[0_0_20px_rgba(232,168,48,0.3)] flex items-center space-x-6">
                    <span className="text-[10px] font-terminal font-bold uppercase tracking-[0.3em] opacity-80 border-r border-fintech-base/20 pr-6">Compute Rating</span>
                    <span className="text-4xl font-editorial font-black">{summary.overall_score}<span className="text-lg opacity-70">/100</span></span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                {/* Sub-Scores */}
                <div className="bg-fintech-surface p-8 rounded-xl border border-fintech-border shadow-[0_10px_20px_rgba(0,0,0,0.3)] flex flex-col justify-center relative">
                    <h3 className="text-[11px] font-terminal uppercase tracking-[0.2em] text-fintech-ash mb-8 flex items-center">
                        <TerminalSquare className="w-4 h-4 mr-3" /> Telemetry Breakdown
                    </h3>
                    
                    <div className="space-y-8">
                        <div>
                            <div className="flex justify-between font-terminal uppercase text-[10px] tracking-widest text-[#63A583] mb-3">
                                <span>Code / Architecture Matrix</span>
                                <span className="font-bold">{summary.technical_score}/100</span>
                            </div>
                            <div className="w-full bg-[#1E212E] rounded h-1.5 shadow-inner border border-fintech-border">
                                <div className="bg-[#63A583] h-1.5 rounded shadow-[0_0_10px_rgba(99,165,131,0.5)]" style={{ width: `${summary.technical_score}%` }}></div>
                            </div>
                        </div>
                        <div>
                            <div className="flex justify-between font-terminal uppercase text-[10px] tracking-widest text-fintech-amber mb-3">
                                <span>Communication Frequency</span>
                                <span className="font-bold">{summary.communication_score}/100</span>
                            </div>
                            <div className="w-full bg-[#1E212E] rounded h-1.5 shadow-inner border border-fintech-border">
                                <div className="bg-fintech-amber h-1.5 rounded shadow-[0_0_10px_rgba(232,168,48,0.5)]" style={{ width: `${summary.communication_score}%` }}></div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Action Panel */}
                <div className="bg-[#1C202E] rounded-xl shadow-[0_15px_30px_rgba(0,0,0,0.5)] border border-fintech-border p-8 flex flex-col justify-between">
                    <div>
                        <h3 className="text-2xl font-editorial text-fintech-cream mb-2">Final Verdict</h3>
                        <p className="text-fintech-ash font-terminal text-[10px] uppercase tracking-widest leading-relaxed">System scan complete. Review protocol nodes below before confirming terminal state.</p>
                    </div>
                    <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4 mt-8">
                        <button className="flex-1 bg-red-500/10 text-red-400 border border-red-500/20 hover:bg-red-500/20 py-4 rounded font-terminal text-[11px] uppercase tracking-[0.2em] font-bold transition-all shadow-inner">
                            Purge Record
                        </button>
                        <button className="flex-1 bg-[#63A583] text-fintech-base hover:bg-[#78C49F] py-4 rounded font-editorial text-lg font-bold shadow-[0_0_15px_rgba(99,165,131,0.2)] transition-all flex items-center justify-center">
                            Promote Node
                        </button>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 pt-4">
                {/* Standout Moments */}
                <div className="bg-[#63A583]/5 rounded-xl border border-[#63A583]/20 overflow-hidden shadow-[inset_0_0_20px_rgba(99,165,131,0.02)]">
                    <div className="bg-[#63A583]/10 px-8 py-5 border-b border-[#63A583]/20 flex items-center text-[#63A583]">
                        <TrendingUp className="w-5 h-5 mr-3" />
                        <h3 className="font-terminal text-[12px] uppercase tracking-[0.2em] font-bold">Positive Deltas</h3>
                    </div>
                    <div className="p-8 space-y-5">
                        {summary.standout_moments.map((item, idx) => (
                            <div key={idx} className="bg-[#1E212E] p-6 rounded border border-fintech-border shadow-[0_5px_15px_rgba(0,0,0,0.3)]">
                                <p className="font-editorial text-lg text-[#63A583] mb-4">{item.moment}</p>
                                <div className="bg-fintech-surface border-l-2 border-[#63A583]/50 pl-4 py-3 font-terminal text-[11px] text-fintech-ash tracking-widest leading-loose">
                                    "{item.transcript_ref}"
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Red Flags */}
                <div className="bg-red-500/5 rounded-xl border border-red-500/20 overflow-hidden shadow-[inset_0_0_20px_rgba(239,68,68,0.02)]">
                    <div className="bg-red-500/10 px-8 py-5 border-b border-red-500/20 flex items-center text-red-400">
                        <AlertTriangle className="w-5 h-5 mr-3" />
                        <h3 className="font-terminal text-[12px] uppercase tracking-[0.2em] font-bold">Critical Warnings</h3>
                    </div>
                    <div className="p-8 space-y-5">
                        {summary.red_flags.map((item, idx) => (
                            <div key={idx} className="bg-[#1E212E] p-6 rounded border border-fintech-border shadow-[0_5px_15px_rgba(0,0,0,0.3)]">
                                <p className="font-editorial text-lg text-red-400 mb-4">{item.moment}</p>
                                <div className="bg-fintech-surface border-l-2 border-red-500/50 pl-4 py-3 font-terminal text-[11px] text-fintech-ash tracking-widest leading-loose">
                                    "{item.transcript_ref}"
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}
